import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const pagesConfig = JSON.parse(readFileSync(new URL('../pages.json', import.meta.url), 'utf8'))
assert.ok(pagesConfig.pages.some(page => page.path === 'pages/sourceHub/sourceHub'))

const sourceHub = readFileSync(new URL('../pages/sourceHub/sourceHub.vue', import.meta.url), 'utf8')
assert.match(sourceHub, /getSourceConfig/)
assert.match(sourceHub, /buildSourceCapability/)
assert.match(sourceHub, /assessSourceBridgeReadiness/)
assert.match(sourceHub, /getSourceSession/)
assert.match(sourceHub, /buildCandidateLanes/)
assert.match(sourceHub, /runSourceAcceptance/)
assert.match(sourceHub, /getSourceAcceptanceReports/)
assert.match(sourceHub, /clearSourceAcceptanceReports/)
assert.match(sourceHub, /buildCopyableAcceptanceReport/)
assert.match(sourceHub, /apiClient/)
assert.match(sourceHub, /openSourceLogin/)
assert.match(sourceHub, /readSourceLoginCookie/)
assert.match(sourceHub, /probeWebViewBridge/)
assert.match(sourceHub, /runRenderedFetchTrial/)
assert.match(sourceHub, /buildRenderedFetchTrialTarget/)
assert.match(sourceHub, /buildAndroidPhonePreflight/)
assert.match(sourceHub, /saveSourceCookie/)
assert.match(sourceHub, /getSourceCookieSummary/)
assert.match(sourceHub, /getSourceSession/)
assert.match(sourceHub, /saveSourceSession/)
assert.match(sourceHub, /deleteSourceSession/)
assert.match(sourceHub, /openExplore/)
assert.match(sourceHub, /runSearch/)
assert.match(sourceHub, /runHubAcceptance/)
assert.match(sourceHub, /copyAcceptanceReport/)
assert.match(sourceHub, /clearAcceptanceReport/)
assert.match(sourceHub, /buildAndroidValidationReport/)
assert.match(sourceHub, /copyAndroidValidationReport/)
assert.match(sourceHub, /androidValidationSummary/)
assert.match(sourceHub, /androidPhonePreflight/)
assert.match(sourceHub, /saveManualSession/)
assert.match(sourceHub, /saveManualSourceSession/)
assert.match(sourceHub, /sourceLoginUrl/)
assert.match(sourceHub, /openAndroidLogin/)
assert.match(sourceHub, /saveAndroidLoginSession/)
assert.match(sourceHub, /cookieSummaryItems/)
assert.match(sourceHub, /syncBackendSession/)
assert.match(sourceHub, /loadBackendSession/)
assert.match(sourceHub, /backendSessionStatusText/)
assert.match(sourceHub, /bridgeReadiness/)
assert.match(sourceHub, /bridgeReadinessStatusText/)
assert.match(sourceHub, /bridgeDiagnosticItems/)
assert.match(sourceHub, /bridgeBlockerItems/)
assert.match(sourceHub, /bridgeProbeReport/)
assert.match(sourceHub, /runBridgeProbe/)
assert.match(sourceHub, /bridgeProbeStatusText/)
assert.match(sourceHub, /sessionBridgeReport/)
assert.match(sourceHub, /sessionBridgeStatusText/)
assert.match(sourceHub, /sessionBridgeMissingText/)
assert.match(sourceHub, /sessionBridgeScope/)
assert.match(sourceHub, /renderedTrialUrl/)
assert.match(sourceHub, /renderedTrialSelector/)
assert.match(sourceHub, /renderedTrialReport/)
assert.match(sourceHub, /renderedTrialTarget/)
assert.match(sourceHub, /applyRenderedTrialTarget/)
assert.match(sourceHub, /bridgeProbeProfileText/)
assert.match(sourceHub, /renderedTrialBridgeText/)
assert.match(sourceHub, /androidValidationItems/)
assert.match(sourceHub, /runRenderedTrial/)
assert.match(sourceHub, /renderedTrialStatusText/)
assert.match(sourceHub, /sourceSessionStatus/)
assert.match(sourceHub, /sessionStatusText/)
assert.match(sourceHub, /acceptanceReport/)
assert.match(sourceHub, /\/pages\/sourceExplore\/sourceExplore\?sourceId=/)
assert.match(sourceHub, /source-hub-page/)
assert.match(sourceHub, /capability-grid/)
assert.match(sourceHub, /session-panel/)
assert.match(sourceHub, /backend-session-state/)
assert.match(sourceHub, /android-session-actions/)
assert.match(sourceHub, /session-bridge-report/)
assert.match(sourceHub, /cookie-summary-list/)
assert.match(sourceHub, /bridge-readiness-panel/)
assert.match(sourceHub, /android-validation-panel/)
assert.match(sourceHub, /android-validation-header/)
assert.match(sourceHub, /android-validation-summary/)
assert.match(sourceHub, /android-phone-preflight/)
assert.match(sourceHub, /phone-preflight-state/)
assert.match(sourceHub, /android-validation-list/)
assert.match(sourceHub, /Android 验证清单/)
assert.match(sourceHub, /复制清单/)
assert.match(sourceHub, /bridge-diagnostic-list/)
assert.match(sourceHub, /bridge-blocker-list/)
assert.match(sourceHub, /bridge-probe-report/)
assert.match(sourceHub, /契约信息/)
assert.match(sourceHub, /rendered-trial-panel/)
assert.match(sourceHub, /rendered-trial-target/)
assert.match(sourceHub, /rendered-trial-report/)
assert.match(sourceHub, /Bridge：/)
assert.match(sourceHub, /会话 Bridge/)
assert.match(sourceHub, /androidValidationItems: this\.androidValidationItems/)
assert.match(sourceHub, /androidValidationSummary: this\.androidValidationSummary/)
assert.match(sourceHub, /androidPhonePreflight: this\.androidPhonePreflight/)
assert.match(sourceHub, /summary: this\.androidValidationSummary/)
assert.match(sourceHub, /phonePreflight: this\.androidPhonePreflight/)
assert.match(sourceHub, /sessionBridgeReport: this\.sessionBridgeReport/)
assert.match(sourceHub, /acceptance-panel/)
assert.match(sourceHub, /acceptance-stage-list/)

const library = readFileSync(new URL('../pages/library/library.vue', import.meta.url), 'utf8')
assert.match(library, /openSourceHub/)
assert.match(library, /\/pages\/sourceHub\/sourceHub\?sourceId=/)
assert.doesNotMatch(library, /@tap="openSourceExplore\(source\)"/)

console.log('sourceHub tests passed')
