import assert from 'node:assert/strict'
import fs from 'node:fs'

const page = fs.readFileSync(new URL('../pages/ttsAcceptance/ttsAcceptance.vue', import.meta.url), 'utf8')
const profile = fs.readFileSync(new URL('../pages/profile/profile.vue', import.meta.url), 'utf8')
const pagesJson = fs.readFileSync(new URL('../pages.json', import.meta.url), 'utf8')

assert.match(pagesJson, /pages\/ttsAcceptance\/ttsAcceptance/)
assert.match(profile, /debugModeEnabled && devPanelVisible/)
assert.match(profile, /openTtsAcceptance/)
assert.match(profile, /\/pages\/ttsAcceptance\/ttsAcceptance\?auto=1/)
assert.match(profile, /@tap="openTtsAcceptance"/)
assert.doesNotMatch(profile, /@tap\.stop="openTtsAcceptance"/)
assert.match(page, /getDebugModeState\(\)\.enabled/)
assert.match(page, /hasToken: !!apiClient\.getToken\(\)/)
assert.match(page, /前往“我的 → 后端服务 → 登录后端”/)
assert.match(page, /不会自动创建账号/)
assert.match(page, /goProfileLogin/)
assert.match(page, /createTtsAcceptanceRunner/)
assert.match(page, /createCloudReadAloudDriver/)
assert.match(page, /createReadAloudDriver/)
assert.match(page, /onLoad\(query = \{\}\)/)
assert.match(page, /setTimeout\(\(\) => this\.runAcceptance\(\), 650\)/)
assert.match(page, /onHide\(\)[\s\S]*runner\.onBackground\(\)/)
assert.match(page, /仅重试后台停止/)
assert.match(page, /runner\.retryBackground\(\)/)
assert.match(page, /ttsAcceptance:lastReport/)
assert.match(page, /runner\.restoreReport\(this\.report\)/)
assert.match(page, /onUnload\(\)[\s\S]*runner\.dispose\(\)/)
assert.match(page, /脱敏报告/)
assert.match(page, /五种真实音色/)
assert.match(page, /三章连续听读/)
assert.match(page, /后台停止/)
assert.match(page, /signal-wave/)
assert.match(page, /prefers-reduced-motion/)

console.log('ttsAcceptanceUi tests passed')
